export const themes = {
  light: {
    title: "light",
    colors: {
      bg: "#f4f4f3",
      bgInvert: "#dcdcdc",
      color: "#1c1c1c",
      colorInvert: "#000000",
      switchBg: "linear-gradient(to bottom, #73bbff, #a2d1fd)",
      sunMoonBg: "#ffc187",
      sunMoonShadow:
        "0 0 11.7px 0 #ffc187, 0 0 20px 0 #ffc18768, -2px -2px 5px 0 #ffab5c inset",
      darkSide: "#ffc187",
      borderGradient: "linear-gradient(to bottom, #a2d1fd, #cde7ff)",
    },
    transitions: {
      bottonWidth: "60%",
      bottomOne: "-55%",
      bottomTwo: "-45%",
      bottomThree: "-40%",
      bottomFour: "-16%",
      leftOne: "0px",
      leftTwo: "15px",
      rightThree: "0px",
      rightFour: "-20px",
      starsTop: "150%",
    },
  },
  dark: {
    title: "dark",
    colors: {
      bg: "#383838",
      bgInvert: "#1c1c1c",
      color: "#ffffff",
      colorInvert: "#f4f4f3",
      switchBg: "linear-gradient(to bottom, #2b3347, #181d27)",
      sunMoonBg: "#dee5f3",
      sunMoonShadow: "0 0 51px 0 #dee5f3",
      darkSide: "#565c6b",
      borderGradient: "linear-gradient(to bottom, #000000, #6c7384)",
    },
    transitions: {
      bottonWidth: "60%",
      bottomOne: "-35%",
      bottomTwo: "-15%",
      bottomThree: "-15%",
      bottomFour: "-5%",
      leftOne: "-110px",
      leftTwo: "-110px",
      rightThree: "-110px",
      rightFour: "-110px",
      starsTop: "50%",
    },
  },
};
